name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Codigo
      uses: actions/checkout@v5

    - name: Configurar Node.js
      uses: actions/setup-node@v5
      with:
        node-version: lts/*

    - name: Instalar Dependencias
      run: npm ci

    - name: Instalar Navegadores do Playwright
      run: npx playwright install --with-deps

    - name: Executar Testes
      run: npx playwright test

    - name: Salvar Relatorio
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30